name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    # Install Node.js and dependencies
    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'  # Specify the Node.js version you want to use

    # Clean up node_modules and package-lock.json before installing
    - name: Clean npm cache and install dependencies
      run: |
        rm -rf node_modules package-lock.json
        npm install --legacy-peer-deps
        npm run build

    # Build the site in the jekyll/builder container
    - name: Build the Jekyll site
      run: |
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll \
        -v ${{ github.workspace }}/build:/srv/jekyll/build \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"

    # Start the application using npm
    - name: Start the application
      run: |
        npm start || echo "Failed to start the application. Check logs for details."

    # View the built file (if needed for debugging purposes)
    - name: List built files
      run: ls -R _site

    # (Optional) Add step to upload built site to GitHub Pages or other deployment
    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_site




# name: Jekyll site CI

# on:
#   push:
#     branches: [ "main" ]
#   pull_request:
#     branches: [ "main" ]

# jobs:
#   build:

#     runs-on: ubuntu-latest

#     steps:
#     - uses: actions/checkout@v4
#     - name: Build the site in the jekyll/builder container
#       run: |
#         docker run \
#         -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
#         jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
