name: Deploy to Vercel

on:
  workflow_dispatch:
  push:
    branches:
      - dev
  pull_request:
    branches:
      - dev

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker image
        run: |
          docker build -t my-app .

      - name: Run Docker container
        run: |
          docker run --name my-app-container -d my-app

      - name: Install Vercel CLI
        run: |
          docker exec my-app-container npm install -g vercel

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          docker exec my-app-container vercel --token $VERCEL_TOKEN --project $VERCEL_PROJECT_ID --confirm --prod

      - name: Stop and remove the Docker container
        run: |
          docker stop my-app-container
          docker rm my-app-container
