name: Deploy to Vercel

on:
  workflow_dispatch:  # Allows manual triggering of this workflow
  push:
    paths:
      - 'frontend/**'
    branches:
      - dev
    tags:
      - v*

  pull_request:
    paths:
      - 'frontend/**'

jobs:
  deploy:
    name: Deploy to Vercel
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.16.0'

      - name: Install dependencies
        run: npm install --force

      - name: Build project
        run: npm run build --force --prefix frontend

      - name: Deploy to Vercel
        env:
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
        run: |
          vercel --token $VERCEL_TOKEN --project $VERCEL_PROJECT_ID --confirm --prod
